"use client"
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import 'slick-carousel/slick/slick.css';
import 'slick-carousel/slick/slick-theme.css';import Navbar from "./components/navbar";
import Footer from "./components/Footer";
import { usePathname } from 'next/navigation';


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {

  const pathname = usePathname();
  
  // Define routes where Navbar and Footer should not appear
  const noLayoutRoutes = ['/login', '/register', '/signup'];
  const showLayout = !noLayoutRoutes.includes(pathname);
  
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
       {showLayout && <Navbar />}
       <main> {children}</main>
        {showLayout && <Footer />}
      </body>
    </html>
  );
}
